### ISSUE TITLE
Using constraints in verification?

### ISSUE THREAD

**Issue by zhanghongce** [berkeley-abc/abc#49]
The output other than the first one can be used for constraints in newer AIGER format , as is used by Yosys when translates `$assume` into AIGER. In `read_aiger` command, parsing of the new header is supported. I wonder if they can be truly used in any verification command in ABC? (I tried and it seemed that `pdr` does not support the extra output as constraints, or I just didn't find the right way...)

**Comment by alanminko** [comment]
If I remember correctly, we need to read the design using &read (rather 
than "read_aiger").  Next we can do the following: "&put; fold; pdr".  
This should add the constraints present in the AIGER format to the 
miter, so that "pdr" can use them.

**Comment by zhanghongce** [comment]
Thank you very much!
